  - name: wait for HAProxy to be up on port 8080
    wait_for:
      port: 8080
  - name: wait for HAProxy to be up on port 80
    wait_for:
      port: 80
  - name: ensure stat page returns 200
    uri:
      url: http://127.0.0.1:8080/