- hosts: all
  gather_facts: true
  become: true
  tasks:
  - import_role:
      name: common
    tags: common

- hosts: load_balancers
  become: true
  tasks:
  - import_role:
      name: haproxy
    tags: haproxy

- hosts: app_servers
  gather_facts: false
  become: true
  tasks:
  - import_role:
      name: tomcat
    tags: tomcat
