- hosts: app_servers
  gather_facts: false
  become: true
  tasks:
  - name: install tomcat
    package:
      name: tomcat8
  - name: start / enable tomcat
    service:
      name: tomcat8
      enabled: true
      state: started
  - name: wait for Tomcat to be up on port 8080
    wait_for:
      port: 8080
  - name: ensure home page returns 200
    uri:
      url: http://127.0.0.1:8080/
      timeout: 240
