- name: Stop tomcat
  service:
    name: tomcat8
    state: stopped

- name: Delete existing webapp
  file:
    name: /var/lib/tomcat8/webapps/{{ tomcat_app_name }}
    state: absent
  

- name: Get application war
  get_url:
    url: "{{ tomcat_app_repository }}/{{ tomcat_app_name }}-{{ tomcat_app_version }}.war"
    dest: /var/lib/tomcat8/webapps/{{ tomcat_app_name }}.war
    force: yes
  notify: Restart tomcat
