- name: install tomcat
  package:
    name: tomcat8

- name: start / enable tomcat
  service:
    name: tomcat8
    enabled: true
    state: started

- name: include tests
  include_tasks: tests.yml
  tags: tests
